language: node_js
node_js:
      - "6"
      - "8"
      - "10"
#before_install: npm install --dev
script: 
    - sed -e "s#@YOUR_PARTNER_ID@#$PARTNER_ID#g" -e "s#@YOUR_ADMIN_SECRET@#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" config.template.json > config.json
    - npm test
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - jonathan.kanarek@kaltura.com
    on_success: change
    on_failure: always
